### ISSUE TITLE
iCub/Vizzy eyes/Gaze support

### ISSUE THREAD

**Issue by traversaro** [robotology/gazebo-yarp-plugins#149]
In this issue we will discuss more in detail what it is needed for implementing a simulation of iCub eyes controlled by the iKinGazeCtrl module. 

## Eye URDF/SDF model : 
At IIT we recently started to set-up a pipeline for automatic extraction of  robot models directly from Creo CAD models, using [SimMechanics Link](http://www.mathworks.it/help/physmod/smlink/index.html) and [simmechanics-to-urdf](https://github.com/robotology-playground/simmechanics-to-urdf). Using this pipeline, we can investigate the extraction of the head/eye kinematic structure directly from CAD.

## Camera simulation support in `gazebo-yarp-plugins`:
Most of the work has been already done by @barbalberto in issue https://github.com/robotology/gazebo-yarp-plugins/issues/96 . The plugin still needs some polishing for supporting all the necessary functionality, but the basic support is already there. 

## Necessary enhancements to `gazebo_yarp_controlboard` plugin.
Currently, only the 3DOF neck mechanism is simulated in Gazebo. The eyes have some peculiarities, for which some modification to the controlboard plugin will be necessary.

### Controlled DOFs
Disregarding details on the actuators placements (as we do in the rest of the Gazebo simulation)
the eye form a quite standard 3DOF tree structure: the first DOF is `eyes_tilt` i.e. the common tilt of the two eyes, while the other 2 DOFs are the two independent "pans" of the two eyes, `left_eye_pan` and `right_eye_pan`. 

You can see this mechanism in this image of the first version of the iCub eyes:  
![eyes](https://cloud.githubusercontent.com/assets/1857049/4891494/829ea8a8-63a8-11e4-9206-81d78fb85de8.png)

However, the yarp controlboard is not controlling independently the two pans, but it is controlling the `eyes_version` and `eyes_vergence`, that are coupled DOFs related to the pans by the following equation (check for reference: http://wiki.icub.org/wiki/Vergence,_Version_and_Disparity):
```
eyes_version    =  left_eye_pan + right_eye_pan
eyes_vergence   =  left_eye_pan - right_eye_pan
```
Note that while the wiki page http://wiki.icub.org/wiki/Vergence,_Version_and_Disparity report a slighty different equation, this equation is the one indicated here, as you can check directly in the iCub firmware source code in `firmware/motorControllerDsp56f807/position_decoupling.c`, line 25 or in  `firmware/motorControllerDsp56f807/pwm_decoupling.c`, line 83. 

### Mixed Position-Velocity control
The iKinGazeCtrl is one of the few (perhaps the only one) controllers in the iCub that uses the new Mixed Position-Velocity Control Mode. In a nutshell this is a low level controlled that accepts both position and velocity commands. This is implemented at low level with a position control and the velocity command is transformed in a *relative* position command by integrating the velocity command and adding it at the current desired position. More details on the iCub/Yarp ControlModes are available in this document: http://wiki.icub.org/images/c/cf/ICub_Control_Modes_1_1.pdf

**Comment by plinioMoreno** [comment]
Hi @traversaro,

The explanation of the way it is implemented is very nice. I remember that you told @mikearagao and me that @hu-yue had started the PID implementation in the control board plugin that is in a branc. Can you confirm this @hu-yue and @traversaro?

This because @carlos-cardoso will work on the version-vergence controller that simulates the control boards' firmware using the gazebo-yarp-plugins.

@traversaro, do you want to add @carlos-cardoso to the robotology organization?

Cheers,

Plinio

**Comment by traversaro** [comment]
Sorry for the late reply @plinioMoreno , 
  yes the local PID implementation was done by @hu-yue for implementing SEA joints simulation. 
 The work is contained in the commits https://github.com/robotology/gazebo-yarp-plugins/commit/8a654c8127a3fe7d2de3633c6551dcdf593e3b54 and https://github.com/robotology/gazebo-yarp-plugins/commit/fab8b285d74a53fbac5f3a09d8ad5849004787c1 .

 Given that the sea branch is a bit stale I think it make sense to extract those changes and open a PR just for implementing the plugin-local PID. I can do it, or perhaps it is a good kick-off task for @carlos-cardoso to start working on gazebo-yarp-plugins.
 I will ask to add him to the team, he may be interested in briefly reviewing the contributing guidelines : https://github.com/robotology/gazebo-yarp-plugins/blob/master/CONTRIBUTING.md

**Comment by plinioMoreno** [comment]
No problem about the late reply @traversaro.

I think your suggestion of the kick-off task sounds good. As soon as 
@carlos-cardoso has something for testing we will let you know.

On 10/5/2015 9:41 AM, Silvio Traversaro wrote:
>
> Sorry for the late reply @plinioMoreno 
> <https://github.com/plinioMoreno> ,
> yes the local PID implementation was done by @hu-yue 
> <https://github.com/hu-yue> for implementing SEA joints simulation.
> The work is contained in the commits 8a654c8 
> <https://github.com/robotology/gazebo-yarp-plugins/commit/8a654c8127a3fe7d2de3633c6551dcdf593e3b54> 
> and fab8b28 
> <https://github.com/robotology/gazebo-yarp-plugins/commit/fab8b285d74a53fbac5f3a09d8ad5849004787c1> 
> .
>
> Given that the sea branch is a bit stale I think it make sense to 
> extract those changes and open a PR just for implementing the 
> plugin-local PID. I can do it, or perhaps it is a good kick-off task 
> for @carlos-cardoso <https://github.com/carlos-cardoso> to start 
> working on gazebo-yarp-plugins.
> I will ask to add him to the team, he may be interested in briefly 
> reviewing the contributing guidelines : 
> https://github.com/robotology/gazebo-yarp-plugins/blob/master/CONTRIBUTING.md
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/robotology/gazebo-yarp-plugins/issues/149#issuecomment-145464298>.
>

-- 
___________________

Plinio Moreno López
http://www.isr.ist.utl.pt/~plinio
plinio@isr.tecnico.ulisboa.pt
___________________

**Comment by plinioMoreno** [comment]
@traversaro , we have a look to the commits 8a654c8 and fab8b28 and it looks like the most important thing was the addition of the [vector of PID controllers](https://github.com/robotology/gazebo-yarp-plugins/commit/fab8b285d74a53fbac5f3a09d8ad5849004787c1#diff-7350f51d09ebea28239e6e684dad73c0R397) and to add the stepTime as a parameter of the ```sendTorqueToGazebo```, just to check if the time elapsed is greater than zero. The PID vector is clear, the less clear is the stepTime, we guess was added this because of some stability reason, isn't it?

@carlos-cardoso has started to understand how the control board plugin works. Starting from the commits above mentioned, he will attempt to do a simple test where a "virtual vergence/version" joint that moves two motors at the same time. Our idea is to have a working example that hardcodes the controller in the case of two predefined joints and send commands, modifying the code in the file [ControlBoardDriver.cpp](https://github.com/robotology/gazebo-yarp-plugins/blob/master/plugins/controlboard/src/ControlBoardDriver.cpp), and using the equations at the [iCub wiki](http://wiki.icub.org/wiki/Vergence,_Version_and_Disparity).

Once we have this working, we need to talk on how to define this special controller in the configuration files of the plugin.

@carlos-cardoso and I want to know what do you think about this idea. If you have suggestions to our approach, let us know. @carlos-cardoso will add that code into the branch [implementingVersionVergenceControllers](https://github.com/robotology/gazebo-yarp-plugins/tree/implementingVersionVergenceControllers).

**Comment by traversaro** [comment]
I am ok with your plan! 

Regarding the `stepTime`, I also don't understand why it was introduced... perhaps for some reason the plugin `OnUpdate` method was called more then once for simulation step? I think @hu-yue can help us on this, but in the meanwhile you can just ignore the stepTime, and check if everything is working anyway.

**Comment by hu-yue** [comment]
I completely missed this, saw it today, sorry.
@plinioMoreno @traversaro the `stepTime` was introduced because it's a parameters that is needed by the the Update function of the `gazebo::common::PID` class (see [here](https://bitbucket.org/osrf/gazebo/src/9559e9655bdaadf4ebd627305713963f871bb0f8/gazebo/common/PID.cc?at=default&fileviewer=file-view-default#PID.cc-110)) that is now used to compute the value for `SetForce`.
The `stepTime` is computed in the `onUpdate` function, see [here](https://github.com/robotology/gazebo-yarp-plugins/blob/sea_joints/plugins/controlboard/src/ControlBoardDriver.cpp#L171).

**Comment by plinioMoreno** [comment]
Hi @traversaro and @randaz81,
unfortunately we did not advance at all. Carlos found a job and left the laboratory and I did not find time to do it.

Let me know any news on the implementation that I will test on Vizzy.

**Comment by randaz81** [comment]
vergence/version control is now implemented by class `EyesCouplingHandler` in `gazebo_yarp_controlboard` plugin. The implementation is based on reference/feedback decoupling, this means that I was able to implemented vergence/version control without modifying anything related to the gazebo PID class. Thus, all the issues related to the proposed enhancements to the gazebo PID class and mentioned in the previous comments should be considered still valid.

Additional notes:
* currently, `mixed mode` is still not implemented (work in progress)
* eyes model in icub sdf is still missing. I was able to test the vergence/version coupled control using a separated test model (see example `gazebo-yarp-plugins\tutorial\model\coupled_pendulum`)

**Comment by randaz81** [comment]
*`mixed mode` control implementation complete.
* implemented missing slew rate limiter on `VelocityMove()` commands. on iCub, reference velocity is not assigned instantaneously, instead it is interpolated from the current velocity to the new reference value according to a trapezoidal profile (the slope is set through `setRefAccelation()` method)
* only icub sdf model is now missing.

**Comment by plinioMoreno** [comment]
@randaz81,

I am going to test your implementation as soon as I can on Vizzy. I just want to know how to create the coupled controller in the configuration file. Thanks!

**Comment by randaz81** [comment]
Just add to your .ini file the following lines:
```
[COUPLING]
eyes_vergence_control (0 1)
```
where 0 1 are the number of the coupled joints.

You can also find an example in `gazebo-yarp-plugins\tutorial\model\coupled_pendulum`

**Comment by randaz81** [comment]
icub.sdf model completed.
Closing issue.
