### ISSUE TITLE
MacOS libraries .dylib VS .so

### ISSUE THREAD

**Issue by iron76** [robotology/gazebo-yarp-plugins#70]
Fresh new installation of gazebo with brew (brew install gazebo --HEAD) seems to automatically search for .dylib regardless of what specified in the .sdf file (currently icub.sdf contains things such as libgazebo_yarp_controlboard.so). To fix the issue I had to change the CMakeLists.txt removing all occurrences of  "add_library MODULE" with "add_library SHARED". I wonder if I can push this change of if this will effect linux users.

**Comment by traversaro** [comment]
Update from https://bitbucket.org/osrf/gazebo/pull-requests/2306/build-plugin-libraries-as-module-instead : apparently since OS X 10.5 both `SHARED` and `MODULE` library can be dynamically loaded and unloaded without any problems. On other platforms (Linux and Windows) there is not difference between the two, so I think we can close this issue until a real problem emerges related to this.
