### ISSUE TITLE
Properly handle joint limits

### ISSUE THREAD

**Issue by traversaro** [robotology/gazebo-yarp-plugins#72]
Currently joint limits for the controlboard are:
  * parsed from the SDF,
  * used only for [IControlLimits](http://wiki.icub.org/yarpdoc /classyarp_1_1dev_1_1IControlLimits.html) interface implementation. 

I propose that:
 * optional "software" limits, stricter that the hardware ones, could be optionally loaded from the .ini configuration files as in the real robots,
 * position input should be saturated to be inside the software limits.

**Comment by randaz81** [comment]
I just implemented the software limits mentioned above.
For example, the joint limits for the icub head (gazebo_icub_head.ini) are:
```
[LIMITS]
jntPosMax  29.0  59.0  54.0  30.0  30.0  50.0
jntPosMin -39.0 -69.0 -54.0 -30.0 -30.0   0.0
jntVelMax 100.0 100.0 100.0 100.0 100.0 100.0
```
* If the section [LIMITS] is missing, limits are taken from the sdf file (a warning message is displayed).
* If the section [LIMITS] is present, all the other parameters (jntPosMax, jntPosMin, jntVelMax) are mandatory.
* Units are deg, deg/s, m, m/s.
* Implementing this section was necessary also because there exist coupled joints whose control limits are different respect to the hardware limits defined in the sdf file (for example eyes vergence/version).
* By now if the section [LIMITS] is missing, a warning message is displayed but the section will become mandatory in the future. So please update all your configurations in time.
* The feature requested by @iron76 is important, it will be implemented asap.

**Comment by randaz81** [comment]
I just implemented the limit enforcer, porting the firmware code to the plugin.
* Some rearrangement of the code will be probably necessary when the new PID class will be implemented.
* The enforcer acts in two ways: 1) generating a new trajectory/position reference if the commanded position exceeds the joint limits. 2) if the joint is controlled in torque mode, the torque reference is replaced by virtual reference that pushes the joint back. This value is computed using the kp gain taken by the position PID.
* Remember to update the icub model to get the new software limits of the joints, now store in the .ini file! Limits values have been taken from iCubGenova02 configuration files.
* Remember to add the [LIMITS] section to other robot models.
