### ISSUE TITLE
New plugin for camera simulation

### ISSUE THREAD

**Issue by EnricoMingo** [robotology/gazebo-yarp-plugins#96]
We should implement plugins for other sensors like kinect, cameras and laser. Is possible to use the ROS versions but to have a completely ROS-free set of plugin we should start to implement them.

**Comment by traversaro** [comment]
@randaz81 and @drdanz today did the first serious test on using the camera plugin for experimenting with the Oculus integration. Random issues spotted:
* [ ] Every captured frame is saved to disk as a png file (dangerous!!)
* [ ] `grabber` and `gazebo_grabber` information need to be hardcoded in all conf files.

**Comment by traversaro** [comment]
Some issue have been fixed in : https://github.com/robotology/gazebo-yarp-plugins/commit/7641bd277e975b98cda1045bcc0a32d7bfd79d5b
  * code style consistency (tab instead of spaces, .. )
  * the "every frame was saved to disk" bug
  * the hardcoded image dimensions 
  * a memory leak in the buffer allocation 

We still have to fix:
 * [ ] The image type (rgb or whatever) is hardcoded

**Comment by traversaro** [comment]
The relevant issues have been solved, if any blocking issue still exist please open a new issue.
